[project]
name = "boxer-validator-airflow"
version = "0.1.0"
description = "Rust library with a Python wrapper managed by uv"
requires-python = ">=3.12"
dependencies = []

[tool.maturin]
module-name = "boxer_validator_airflow._core"
python-packages = ["boxer_validator_airflow"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
