from typing import Any, Awaitable

class BoxerPrincipal:
    def get_id(self) -> str: ...
    def get_name(self) -> str: ...
    def serialize_user(self) -> dict[str, str]: ...
    @staticmethod
    def deserialize_user(token: dict[str, Any]) -> BoxerPrincipal: ...

class Boxer:
    def __init__(self) -> None: ...
    def get_url_login(self, kwargs: dict[str, Any]) -> str: ...
    def create_token(self, external_token: str) -> Awaitable[dict[str, str]]: ...
    def filter_authorized_menu_items(self, menu_items: list[Any], user_id: str) -> list[Any]: ...
    def is_authorized_asset(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_asset_alias(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_configuration(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_connection(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_custom_view(self, method: str, resource_name: str, user_id: str) -> bool: ...
    def is_authorized_dag(
        self,
        method: str,
        user_id: str,
        access_entity: Any | None = None,
        details: Any | None = None,
    ) -> bool: ...
    def is_authorized_pool(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_variable(self, method: str, user_id: str, details: Any | None = None) -> bool: ...
    def is_authorized_view(self, access_view: Any, user_id: str) -> bool: ...
