from typing import Any

class BoxerPrincipal:
    def get_id(self) -> str: ...
    def get_name(self) -> str: ...
    def serialize_user(self) -> dict[str, str]: ...
    @staticmethod
    def deserialize_user(token: dict[str, Any]) -> BoxerPrincipal: ...

def get_url_login(kwargs: dict[str, Any]) -> str: ...
def filter_authorized_menu_items(menu_items: list[Any], user_id: str) -> list[Any]: ...
def is_authorized_asset(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_asset_alias(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_configuration(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_connection(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_custom_view(method: str, resource_name: str, user_id: str) -> bool: ...
def is_authorized_dag(
    method: str,
    user_id: str,
    access_entity: Any | None = None,
    details: Any | None = None,
) -> bool: ...
def is_authorized_pool(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_variable(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_view(access_view: Any, user_id: str) -> bool: ...
