from typing import Any

def serialize_user(user_id: str, name: str) -> dict[str, str]: ...
def deserialize_user(token: dict[str, Any]) -> tuple[str, str]: ...
def get_url_login(kwargs: dict[str, Any]) -> str: ...
def filter_authorized_menu_items(menu_items: list[Any], user_id: str) -> list[Any]: ...
def is_authorized_asset(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_asset_alias(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_configuration(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_connection(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_custom_view(method: str, resource_name: str, user_id: str) -> bool: ...
def is_authorized_dag(
    method: str,
    user_id: str,
    access_entity: Any | None = None,
    details: Any | None = None,
) -> bool: ...
def is_authorized_pool(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_variable(method: str, user_id: str, details: Any | None = None) -> bool: ...
def is_authorized_view(access_view: Any, user_id: str) -> bool: ...
